version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: xlab_race_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_CLIENT_CHARSET: utf8mb4
    expose:
      - 3306
    ports:
      - "3307:3306"
    networks:
      - my_network

  xlab_race_spider:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    command: python main.py
    volumes:
      - log:/spider/log
    depends_on:
      - mysql
    networks:
      - my_network

volumes:
  mysql-data:
  log:

networks:
  my_network: