feishu:
  appId: 
  appSecret: 
  encryptKey: 
  verificationToken: 
  larkHost: "https://open.feishu.cn"

server:
  port: 8000

db:
  host: "mysql"
  port: "3306"
  user: "root"
  password: "123456"
  dbName: "xlab_comp_db"